### ISSUE TITLE
Attribute Error on Ubuntu

### ISSUE THREAD

**Issue by iveoles** [invernizzi/hiplogging#5]
Hi

I receive an error when trying to run the example. We're running Python 2.7.6 on Ubuntu 14.04. I've pasted the error below

python example.py
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    import hiplogging
  File "/root/hipchat/hiplogging-master/hiplogging/__init__.py", line 6, in <module>
    import hipchat
  File "/root/hipchat/hiplogging-master/hipchat.py", line 11, in <module>
    handler = hiplogging.HipChatHandler('<TOKEN>',
AttributeError: 'module' object has no attribute 'HipChatHandler'

**Comment by invernizzi** [comment]
Hi Adam,
thanks for the bug report. The problem there is that you cannot name your file 'hipchat.py': anything else is fine. If you do that, python will load your file as a module, instead of the 'real' hipchat module. It's a sneaky bug.

Proof: on a fresh Ubuntu 14.04, I've executed with no errors:

```bash
export HIPCHAT_ADMIN_TOKEN='XXXXXXXXXXXXX'
export HIPCHAT_ROOM='testing room'
sudo aptitude install python-pip
sudo pip install hiplogging
wget 'https://raw.githubusercontent.com/invernizzi/hiplogging/master/example.py'
python example.py
```

But just
```bash
mv example.py hipchat.py
python hipchat.py 
```
and you'll get

```python
Traceback (most recent call last):
  File "hipchat.py", line 3, in <module>
    import hiplogging
  File "/usr/local/lib/python2.7/dist-packages/hiplogging/__init__.py", line 6, in <module>
    import hipchat
  File "/home/vagrant/hipchat.py", line 11, in <module>
    handler = hiplogging.HipChatHandler(os.environ['HIPCHAT_ADMIN_TOKEN'],
AttributeError: 'module' object has no attribute 'HipChatHandler'
```

So, just rename your file to anything else.
Ciao!
  Luca

**Comment by iveoles** [comment]
This file name in my command above was example.py

python example.py
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    import hiplogging
  File "build/bdist.linux-x86_64/egg/hiplogging/__init__.py", line 6, in <module>
  File "/root/hipchat.py", line 11, in <module>
AttributeError: 'module' object has no attribute 'HipChatHandler'

**Comment by invernizzi** [comment]
Hi Adam,
that's great, but you have a /root/hipchat.py module that is being loaded instead of the python-simple-hipchat library, which this library depends upon. Try renaming that file, and everything should work out fine.
